---
- name: Add Homebrew taps
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_taps }}"
  when: homebrew_taps | length > 0

- name: Install Homebrew formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_formulae }}"

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_casks }}"

- name: Install Mac App Store apps
  community.general.mas:
    id: "{{ item.id }}"
    state: present
  loop: "{{ mas_apps }}"
  when: mas_apps | length > 0
